# Generated by Django 3.2 on 2021-04-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boardgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('year_published', models.IntegerField()),
                ('min_players', models.IntegerField()),
                ('edition', models.FloatField()),
            ],
        ),
    ]
