# Generated by Django 3.2 on 2021-04-19 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0004_auto_20210419_0853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Play_To_Players',
            new_name='Play_To_Player',
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boardgames.category'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='edition',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='max_players',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='min_players',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='year_published',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='winning_player_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
