# Generated by Django 3.2 on 2021-04-20 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0005_auto_20210419_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='boardgame_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardgames.boardgame'),
        ),
    ]
