# Generated by Django 3.2 on 2021-04-20 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0006_alter_play_boardgame_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='winning_player_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boardgames.player'),
        ),
    ]
